version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Host=db;Database=financepersonal;Username=postgres;Password=postgres;
      - ASPNETCORE_ENVIRONMENT=Production
      - JwtSettings__Key=S3cr3t_K3y!Financial_Manager@2025_S3cur1ty_T0k3n
      - JwtSettings__Issuer=FinanceManagerAPI
      - JwtSettings__Audience=FinanceManagerClient
    networks:
      - finance-network
    volumes:
      - ./logs:/app/logs

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=financepersonal
    networks:
      - finance-network

networks:
  finance-network:
    driver: bridge

volumes:
  postgres_data:
